### ISSUE TITLE
Right mouse button does not work

### ISSUE THREAD

**Issue by Sir-Zodiac** [SukkoPera/OpenAmigaJoyMouseSwitcher#7]
I testet 2 mice in OS 3.9 with an Amiga 1200 rev.2B and the switcher is Version 1.2 Without the switcher they both work fine. With the switcher the right mouse button is not recognized. I removed the jumpers but no luck.
The mice are a Logitech PS2 with a Cocolino and a Dell USB/PS2 Mouse with a Micromys V5 Adapter.

**Comment by SukkoPera** [comment]
Does your board have 5 o 6 diodes close to the output connector? What chip did you use for U1?

**Comment by Sir-Zodiac** [comment]
I bought it from Ebay. At the single connector end I see 5 diodes.
I assume the chip next to the diodes is U1. It reads SN74LS08N.
I see that C5 is not soldered onto the board.

**Comment by SukkoPera** [comment]
Ok, I don't mean to be rude, but you should ask the seller for help. I'm tired of selfish people making money off my back, never contributing anything to my projects, using components of doubious origin and then leaving it all to me when it comes to support.

I'm sorry, but he got the money, he owes you support.
